// Code generated by suave/gen. DO NOT EDIT.
// Hash: 40fc861438d8634a16c81f5a373c54f4e760944ed185a10b66a7bc7e6424645d
package artifacts

import (
	"github.com/ethereum/go-ethereum/common"
)

// List of suave precompile addresses
var (
	buildEthBlockAddr            = common.HexToAddress("0x0000000000000000000000000000000042100001")
	confidentialInputsAddr       = common.HexToAddress("0x0000000000000000000000000000000042010001")
	confidentialRetrieveAddr     = common.HexToAddress("0x0000000000000000000000000000000042020001")
	confidentialStoreAddr        = common.HexToAddress("0x0000000000000000000000000000000042020000")
	ethcallAddr                  = common.HexToAddress("0x0000000000000000000000000000000042100003")
	extractHintAddr              = common.HexToAddress("0x0000000000000000000000000000000042100037")
	fetchBidsAddr                = common.HexToAddress("0x0000000000000000000000000000000042030001")
	fillMevShareBundleAddr       = common.HexToAddress("0x0000000000000000000000000000000043200001")
	newBidAddr                   = common.HexToAddress("0x0000000000000000000000000000000042030000")
	randomUintAddr               = common.HexToAddress("0x00000000000000000000000000000000F00bA777")
	secp256k1RecoverPubkeyAddr   = common.HexToAddress("0x9000000000000000000000000000000000000002")
	secp256k1SignAddr            = common.HexToAddress("0x9000000000000000000000000000000000000001")
	secp256k1VerifySignatureAddr = common.HexToAddress("0x9000000000000000000000000000000000000003")
	signEthTransactionAddr       = common.HexToAddress("0x0000000000000000000000000000000040100001")
	simulateBundleAddr           = common.HexToAddress("0x0000000000000000000000000000000042100000")
	submitBundleJsonRPCAddr      = common.HexToAddress("0x0000000000000000000000000000000043000001")
	submitEthBlockBidToRelayAddr = common.HexToAddress("0x0000000000000000000000000000000042100002")
)

var SuaveMethods = map[string]common.Address{
	"buildEthBlock":            buildEthBlockAddr,
	"confidentialInputs":       confidentialInputsAddr,
	"confidentialRetrieve":     confidentialRetrieveAddr,
	"confidentialStore":        confidentialStoreAddr,
	"ethcall":                  ethcallAddr,
	"extractHint":              extractHintAddr,
	"fetchBids":                fetchBidsAddr,
	"fillMevShareBundle":       fillMevShareBundleAddr,
	"newBid":                   newBidAddr,
	"randomUint":               randomUintAddr,
	"secp256k1RecoverPubkey":   secp256k1RecoverPubkeyAddr,
	"secp256k1Sign":            secp256k1SignAddr,
	"secp256k1VerifySignature": secp256k1VerifySignatureAddr,
	"signEthTransaction":       signEthTransactionAddr,
	"simulateBundle":           simulateBundleAddr,
	"submitBundleJsonRPC":      submitBundleJsonRPCAddr,
	"submitEthBlockBidToRelay": submitEthBlockBidToRelayAddr,
}

func PrecompileAddressToName(addr common.Address) string {
	switch addr {
	case buildEthBlockAddr:
		return "buildEthBlock"
	case confidentialInputsAddr:
		return "confidentialInputs"
	case confidentialRetrieveAddr:
		return "confidentialRetrieve"
	case confidentialStoreAddr:
		return "confidentialStore"
	case ethcallAddr:
		return "ethcall"
	case extractHintAddr:
		return "extractHint"
	case fetchBidsAddr:
		return "fetchBids"
	case fillMevShareBundleAddr:
		return "fillMevShareBundle"
	case newBidAddr:
		return "newBid"
	case randomUintAddr:
		return "randomUint"
	case secp256k1RecoverPubkeyAddr:
		return "secp256k1RecoverPubkey"
	case secp256k1SignAddr:
		return "secp256k1Sign"
	case secp256k1VerifySignatureAddr:
		return "secp256k1VerifySignature"
	case signEthTransactionAddr:
		return "signEthTransaction"
	case simulateBundleAddr:
		return "simulateBundle"
	case submitBundleJsonRPCAddr:
		return "submitBundleJsonRPC"
	case submitEthBlockBidToRelayAddr:
		return "submitEthBlockBidToRelay"
	}
	return ""
}
