env:
  - CGO_ENABLED=1
builds:
  - id: suave-geth-darwin-amd64
    binary: suave-geth
    main: ./cmd/geth
    goarch:
      - amd64
    goos:
      - darwin
    env:
      - CC=o64-clang
      - CXX=o64-clang++
    flags:
      - -trimpath
  - id: suave-geth-darwin-arm64
    binary: suave-geth
    main: ./cmd/geth
    goarch:
      - arm64
    goos:
      - darwin
    env:
      - CC=oa64-clang
      - CXX=oa64-clang++
    flags:
      - -trimpath
  - id: suave-geth-linux-amd64
    binary: suave-geth
    main: ./cmd/geth
    env:
      - CC=x86_64-linux-gnu-gcc
      - CXX=x86_64-linux-gnu-g++
    goarch:
      - amd64
    goos:
      - linux
    flags:
      - -trimpath
    ldflags:
      - -extldflags "-Wl,-z,stack-size=0x800000 --static"
    tags:
      - netgo
      - osusergo
  - id: suave-geth-linux-arm64
    binary: suave-geth
    main: ./cmd/geth
    goarch:
      - arm64
    goos:
      - linux
    env:
      - CC=aarch64-linux-gnu-gcc
      - CXX=aarch64-linux-gnu-g++
    flags:
      - -trimpath
    ldflags:
      - -extldflags "-Wl,-z,stack-size=0x800000 --static"
    tags:
      - netgo
      - osusergo
  - id: suave-geth-windows-amd64
    binary: suave-geth
    main: ./cmd/geth
    goarch:
      - amd64
    goos:
      - windows
    env:
      - CC=x86_64-w64-mingw32-gcc
      - CXX=x86_64-w64-mingw32-g++
    flags:
      - -trimpath
      - -buildmode=exe

archives:
  - id: w/version
    builds:
      - suave-geth-darwin-amd64
      - suave-geth-darwin-arm64
      - suave-geth-linux-amd64
      - suave-geth-linux-arm64
      - suave-geth-windows-amd64
    name_template: "suave-geth_v{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    wrap_in_directory: false
    format: zip
    files:
      - none*

dockers:
  - dockerfile: ./Dockerfile.suave
    use: buildx
    goarch: amd64
    goos: linux
    build_flag_templates:
      - --platform=linux/amd64
    image_templates:
      - "flashbots/suave-geth:{{ .ShortCommit }}-amd64"
      - "flashbots/suave-geth:{{ .Tag }}-amd64"
      - "flashbots/suave-geth:latest-amd64"
  - dockerfile: ./Dockerfile.suave
    use: buildx
    goarch: arm64
    goos: linux
    build_flag_templates:
      - --platform=linux/arm64
    image_templates:
      - "flashbots/suave-geth:{{ .ShortCommit }}-arm64"
      - "flashbots/suave-geth:{{ .Tag }}-arm64"
      - "flashbots/suave-geth:latest-arm64"

docker_manifests:
  - name_template: "flashbots/suave-geth:{{ .ShortCommit }}"
    image_templates:
      - "flashbots/suave-geth:{{ .ShortCommit }}-amd64"
      - "flashbots/suave-geth:{{ .ShortCommit }}-arm64"
  - name_template: "flashbots/suave-geth:{{ .Tag }}"
    image_templates:
      - "flashbots/suave-geth:{{ .Tag }}-amd64"
      - "flashbots/suave-geth:{{ .Tag }}-arm64"
  - name_template: "flashbots/suave-geth:latest"
    image_templates:
      - "flashbots/suave-geth:latest-amd64"
      - "flashbots/suave-geth:latest-arm64"

checksum:
  name_template: "checksums.txt"

release:
  draft: true
  header: |
    # 🚀 Features
    # 🎄 Enhancements
    # 🐞 Notable bug fixes
    # 🎠 Community
