// Code generated by github.com/fjl/gencodec. DO NOT EDIT.

package types

import (
	"encoding/json"

	"github.com/ethereum/go-ethereum/common/hexutil"
)

var _ = (*httpRequestMarshaling)(nil)

// MarshalJSON marshals as JSON.
func (h HttpRequest) MarshalJSON() ([]byte, error) {
	type HttpRequest struct {
		Url                    string
		Method                 string
		Headers                []string
		Body                   hexutil.Bytes
		WithFlashbotsSignature bool
	}
	var enc HttpRequest
	enc.Url = h.Url
	enc.Method = h.Method
	enc.Headers = h.Headers
	enc.Body = h.Body
	enc.WithFlashbotsSignature = h.WithFlashbotsSignature
	return json.Marshal(&enc)
}

// UnmarshalJSON unmarshals from JSON.
func (h *HttpRequest) UnmarshalJSON(input []byte) error {
	type HttpRequest struct {
		Url                    *string
		Method                 *string
		Headers                []string
		Body                   *hexutil.Bytes
		WithFlashbotsSignature *bool
	}
	var dec HttpRequest
	if err := json.Unmarshal(input, &dec); err != nil {
		return err
	}
	if dec.Url != nil {
		h.Url = *dec.Url
	}
	if dec.Method != nil {
		h.Method = *dec.Method
	}
	if dec.Headers != nil {
		h.Headers = dec.Headers
	}
	if dec.Body != nil {
		h.Body = *dec.Body
	}
	if dec.WithFlashbotsSignature != nil {
		h.WithFlashbotsSignature = *dec.WithFlashbotsSignature
	}
	return nil
}
