// Code generated by suave/gen. DO NOT EDIT.
// Hash: 8360292e97290791f5370456038098e833b1547c2ba26fb79e883641f4510cd4
package types

import "github.com/ethereum/go-ethereum/common"

// Structs

type Bid struct {
	Id                  [32]byte
	DecryptionCondition uint64
	AllowedPeekers      []common.Address
	AllowedStores       []common.Address
	Version             string
}

type BuildBlockArgs struct {
	Slot           uint64
	ProposerPubkey []byte
	Parent         [32]byte
	Timestamp      uint64
	FeeRecipient   common.Address
	GasLimit       uint64
	Random         [32]byte
	Withdrawals    []*Withdrawal
}

type Withdrawal struct {
	Index     uint64
	Validator uint64
	Address   common.Address
	Amount    uint64
}
