// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: proto/suavesdk.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Suave_Call_FullMethodName = "/proto.Suave/Call"
)

// SuaveClient is the client API for Suave service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SuaveClient interface {
	Call(ctx context.Context, in *CallRequest, opts ...grpc.CallOption) (*CallResponse, error)
}

type suaveClient struct {
	cc grpc.ClientConnInterface
}

func NewSuaveClient(cc grpc.ClientConnInterface) SuaveClient {
	return &suaveClient{cc}
}

func (c *suaveClient) Call(ctx context.Context, in *CallRequest, opts ...grpc.CallOption) (*CallResponse, error) {
	out := new(CallResponse)
	err := c.cc.Invoke(ctx, Suave_Call_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SuaveServer is the server API for Suave service.
// All implementations should embed UnimplementedSuaveServer
// for forward compatibility
type SuaveServer interface {
	Call(context.Context, *CallRequest) (*CallResponse, error)
}

// UnimplementedSuaveServer should be embedded to have forward compatible implementations.
type UnimplementedSuaveServer struct {
}

func (UnimplementedSuaveServer) Call(context.Context, *CallRequest) (*CallResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Call not implemented")
}

// UnsafeSuaveServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SuaveServer will
// result in compilation errors.
type UnsafeSuaveServer interface {
	mustEmbedUnimplementedSuaveServer()
}

func RegisterSuaveServer(s grpc.ServiceRegistrar, srv SuaveServer) {
	s.RegisterService(&Suave_ServiceDesc, srv)
}

func _Suave_Call_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CallRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SuaveServer).Call(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Suave_Call_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SuaveServer).Call(ctx, req.(*CallRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Suave_ServiceDesc is the grpc.ServiceDesc for Suave service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Suave_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Suave",
	HandlerType: (*SuaveServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Call",
			Handler:    _Suave_Call_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/suavesdk.proto",
}
