name: Checks

on:
  push:
    branches: [main]
  pull_request:

env:
  CGO_CFLAGS_ALLOW: "-O -D__BLST_PORTABLE__"
  CGO_CFLAGS: "-O -D__BLST_PORTABLE__"

jobs:
  lint:
    name: Lint and test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21.1
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Install golangci-lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.51.2

      - name: Lint
        run: make lint

      - name: Lint contracts
        run: cd suave && forge fmt --check

      - name: Build contracts
        run: cd suave && forge build

      - name: Test
        run: go test ./accounts ./cmd/geth ./core ./core/types ./core/vm ./eth/... ./internal/ethapi/... ./les/... ./miner ./params ./suave/...

      - name: Ensure go mod tidy runs without changes
        run: |
          go mod tidy
          git diff-index HEAD
          git diff-index --quiet HEAD

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v3
        with:
          go-version: ^1.20
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Build
        run: make geth

  devenv:
    name: Devenv
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v3
        with:
          go-version: ^1.20
        id: go

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Build contracts
        run: cd suave && forge build

      - name: Run dev environment
        run: make devnet-up

      - name: Run mev-share example
        run: go run suave/devenv/cmd/main.go
