name: Release

on:
  push:
    branches: [main]
  pull_request:

env:
  CGO_CFLAGS_ALLOW: "-O -D__BLST_PORTABLE__"
  CGO_CFLAGS: "-O -D__BLST_PORTABLE__"

jobs:
  gh-release:
    name: Generate artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ^1.20
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Build artifacts
        run: ./suave/scripts/build-release.sh
