# .github/workflows/release.yml
name: release

on:
  workflow_dispatch:
  push:
    tags:
      - "*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: setup dependencies
        uses: actions/setup-go@v2

      - name: Login to Docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.FLASHBOTS_DOCKERHUB_USERNAME }}
          password: ${{ secrets.FLASHBOTS_DOCKERHUB_TOKEN }}

      - name: Log tag name
        run: echo "Build for tag ${{ github.ref_name }}"

      - name: Validate tag and version
        run: |
          make suave
          version=$(./build/bin/suave-geth version | grep '^Version:' | awk -F': ' '{print "v" $2}')
          if [ "$version" != "${{ github.ref_name }}" ]; then
            echo "Version mismatch: $version != ${{ github.ref_name }}"
            exit 1
          fi

      - name: Create release
        run: make release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ github.ref_name }}
